In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

print(sys.executable)

/home/wholsum/Documents/Padhai/CDAC-AI/CDAC-AI-Data_Analytics/.venv/bin/python

In [6]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns = ['A', 'B', 'C'], index = ['x', 'y', 'z', 'w'])
print('Head: ', df.head())
print('-'*60)
print('Sample: ', df.sample(3)) # for random rows
print('-'*60)
print('Shape: ', df.shape)
print('-'*60)
print('info: \n', df.info)
print('-'*60)
print('describe: \n', df.describe())
print('-'*60)
print('index: ', df.index)
print('-'*60)

Head:      A   B   C
x   1   2   3
y   4   5   6
z   7   8   9
w  10  11  12
------------------------------------------------------------
Sample:      A   B   C
x   1   2   3
y   4   5   6
w  10  11  12
------------------------------------------------------------
Shape:  (4, 3)
------------------------------------------------------------
info:
 <bound method DataFrame.info of     A   B   C
x   1   2   3
y   4   5   6
z   7   8   9
w  10  11  12>
------------------------------------------------------------
describe:
                A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000
------------------------------------------------------------
index:  Index(['x', 'y', 'z', 'w'], dtype='str')
------------------------------------------------------------

# Loading and Accessing Data from a `.csv` file

In [6]:
# loading
coffee = pd.read_csv('coffee.csv')
results_p = pd.read_parquet('results.parquet')
bios = pd.read_csv('bios.csv')


# accessing
print(coffee.sample(10, random_state = 1)) # to make data deterministic we use random_state
print('-'*60)
# loc => filter dataframes by rows and columns and iloc 
print(coffee.loc[5:13]) 
print('-'*60)
print(coffee.iloc[5:13,[0,2]]) # uses only index values
print('-'*60)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35
------------------------------------------------------------
          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35
------------------------------------------------------------
          Day  Units Sold
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
------------------------------------------------------------

# Adding and Removing Columns

In [7]:
coffee_new = coffee.copy()
coffee_new['price'] = 4.99
coffee_new['new_price'] = np.where(coffee_new['Coffee Type'] == 'Espressor', 3.99, 5.99)

coffee_new.drop(columns=['price'], inplace = True)
# print(coffee_new)
# print('-'*60)

coffee_new['revenue'] = coffee_new['Units Sold'] * coffee_new['new_price']
# print(coffee_new['revenue'])
# print('-'*60)


coffee_new.rename(columns = {'new_price': 'price'}, inplace = True)
# print(coffee_new)
# print('-'*60)

bios_new = bios.copy()

print(bios_new.head())
print('-'*60)
bios_new['first name'] = bios_new['name'].str.split(" ").str[0]
display(bios_new)

bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date']) # errors and format parameter
display(bios_new)
print(bios_new.info)

   athlete_id                   name   born_date    born_city  \
0           1  Jean-François Blanchy  1886-12-12     Bordeaux
1           2         Arnaud Boetsch  1969-04-01       Meulan
2           3           Jean Borotra  1898-08-13     Biarritz
3           4        Jacques Brugnon  1895-05-11  Paris VIIIe
4           5           Albert Canet  1878-04-17   Wandsworth

            born_region born_country     NOC  height_cm  weight_kg   died_date
0               Gironde          FRA  France        NaN        NaN  1960-10-02
1              Yvelines          FRA  France      183.0       76.0         NaN
2  Pyrénées-Atlantiques          FRA  France      183.0       76.0  1994-07-17
3                 Paris          FRA  France      168.0       64.0  1978-03-20
4               England          GBR  France        NaN        NaN  1930-07-25
------------------------------------------------------------

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

<bound method DataFrame.info of         athlete_id                   name   born_date        born_city  \
0                1  Jean-François Blanchy  1886-12-12         Bordeaux
1                2         Arnaud Boetsch  1969-04-01           Meulan
2                3           Jean Borotra  1898-08-13         Biarritz
3                4        Jacques Brugnon  1895-05-11      Paris VIIIe
4                5           Albert Canet  1878-04-17       Wandsworth
...            ...                    ...         ...              ...
145495      149222      Polina Luchnikova  2002-01-30            Serov
145496      149223    Valeriya Merkusheva  1999-09-20  Moskva (Moscow)
145497      149224        Yuliya Smirnova  1998-05-08           Kotlas
145498      149225         André Foussard  1899-05-19            Niort
145499      149814          Bill Phillips  1913-07-15     Dulwich Hill

                 born_region born_country        NOC  height_cm  weight_kg  \
0                    Gironde          FRA     France        NaN        NaN
1                   Yvelines          FRA     France      183.0       76.0
2       Pyrénées-Atlantiques          FRA     France      183.0       76.0
3                      Paris          FRA     France      168.0       64.0
4                    England          GBR     France        NaN        NaN
...                      ...          ...        ...        ...        ...
145495            Sverdlovsk          RUS        ROC      167.0       61.0
145496                Moskva          RUS        ROC      168.0       65.0
145497           Arkhangelsk          RUS        ROC      163.0       55.0
145498           Deux-Sèvres          FRA     France      166.0        NaN
145499       New South Wales          AUS  Australia        NaN        NaN

         died_date     first name born_datetime
0       1960-10-02  Jean-François    1886-12-12
1              NaN         Arnaud    1969-04-01
2       1994-07-17           Jean    1898-08-13
3       1978-03-20        Jacques    1895-05-11
4       1930-07-25         Albert    1878-04-17
...            ...            ...           ...
145495         NaN         Polina    2002-01-30
145496         NaN       Valeriya    1999-09-20
145497         NaN         Yuliya    1998-05-08
145498  1986-03-18          André    1899-05-19
145499  2003-10-20           Bill    1913-07-15

[145500 rows x 12 columns]>

# Merging and Concatenating Data

In [43]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [68]:
noc = pd.read_csv('noc_regions.csv')
bios = pd.read_csv('bios.csv')
results = pd.read_csv('results.csv')

# merging
bios_new2 = pd.merge(bios, noc, left_on = 'born_country', right_on = 'NOC', how = 'left')
bios_new2.rename(columns = { 'region': 'born_country_full'}, inplace = True)
bios_new2[bios_new2['NOC_x'] != bios_new2['born_country_full']][['name', 'NOC_x', 'born_country_full']]

usa = bios_new2[bios_new2['born_country'] == 'USA'].copy()
gbr = bios_new2[bios_new2['born_country'] == 'GBR'].copy()

new_df = pd.concat([usa,gbr])

# display(new_df.head())
# display(new_df.tail())

combined_df = pd.merge(results, bios, on = 'athlete_id', how = 'left')
# combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

# Handling Null Values

In [77]:
coffee.loc[[2,3], 'Units Sold'] = np.nan
coffee.isna().sum()

coffee_new2 = coffee.copy()
coffee_new2.fillna(coffee_new2['Units Sold'].interpolate()) 
# interpolate reads patterns in the data and continues that pattern in the data

       Day Coffee Type  Units Sold
0   Monday    Espresso         NaN
1   Monday       Latte         NaN
2  Tuesday    Espresso         NaN
3  Tuesday       Latte         NaN

# Aggregate Data

In [ ]:
bios_new2[bios_new2['born_country'] == 'USA']['born_region'].value_counts()

# cause coffee_new has price parameter
coffee_new.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price': 'mean',})

pivot = coffee_new.pivot(columns = 'Coffee Type', index = 'Day', values = 'revenue')

pivot.loc['Monday', 'Latte']
pivot.sum()
pivot.sum(axis = 1)

bios_new['born_date'] = pd.to_datetime(bios['born_date'])
bios_new.groupby(bios_new['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending = False)

# Advance Functionality

In [12]:
coffee_new['yesterday_revenue'] = coffee_new['revenue'].shift(2)
display(coffee_new['yesterday_revenue'])

bios['height_rank'] = bios['height_cm'].rank()
bios['height_rank'] = bios.sort_values(['height_cm'], ascending= False)

0        NaN
1        NaN
2     149.75
3      89.85
4     179.70
5     119.80
6     209.65
7     149.75
8     239.60
9     179.70
10    269.55
11    209.65
12    269.55
13    209.65
Name: yesterday_revenue, dtype: float64

ValueError: Columns must be same length as key